### create moderator
POST http://{{app-server-url}}/api/auth/signup
Content-Type: application/json

{
  "username": "mod",
  "email": "mod@kimoror.com",
  "password": "12345678",
  "role": ["mod"]
}

### create administrator
POST http://{{app-server-url}}/api/auth/signup
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@kimoror.com",
  "password": "12345678",
  "role": ["admin"]
}

###create user
POST http://{{app-server-url}}/api/auth/signup
Content-Type: application/json

{
  "username": "user",
  "email": "user@kimoror.com",
  "password": "12345678",
  "role": ["user"]
}

###create user and moderator
POST http://{{app-server-url}}/api/auth/signup
Content-Type: application/json

{
  "username": "userAndModer",
  "email": "userAndModer@kimoror.com",
  "password": "12345678",
  "role": ["userAndModer"]
}